name: Execute a lueur scenario file

on:
  workflow_dispatch:

jobs:
  run-reliability-scenario:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: rebound-how/actions/lueur@main
      with:
        scenario: lueur
        report: report.md
        results: results.json
