name: Execute a lueur scenario file

on:
  workflow_dispatch:

jobs:
  run-reliability-scenario:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install demo
      shell: bash
      run: |
        curl -s -Lo $HOME/lueur-app https://github.com/Lawouach/demo/releases/download/1/lueur
        chmod +x $HOME/lueur-app

        RUNNER_TRACKING_ID="" && (nohup $HOME/lueur-app demo run &)
  
    - uses: rebound-how/actions/lueur@main
      with:
        scenario: lueur
        report: report.md
        result: results.json

    - name: Terminate demo
      shell: bash
      run: |
        killall lueur-app
  